technex-iit-bhu/CA_Frontend

- .prettierrc.json
- README.md
- next.config.js
- package-lock.json
- package.json
- postcss.config.js
- src/components/contactus.tsx
- src/components/footer.tsx
- src/components/layout.tsx
- src/pages/_app.tsx
- src/pages/_document.tsx
- src/pages/api/hello.ts
- src/pages/index.tsx
- src/pages/ourReach.tsx
- src/styles/style.css
- tailwind.config.ts
- tsconfig.json
Tasks done : 
--
+ Created complete page.
+ Added Transition with 800ms delay.
+ Improve Code Quality.
Tasks remaining -
-- 
+ Distribute various components and integrate it back to `ourReach.tsx`.
+ We'll need to raise a final PR at last for merging common components once all components of langing page are complete.
Fixes #6
> Enhancement: Created `ourReach.tsx` Page

- src/components/abouttechnex.tsx
- src/components/accordiantheme.tsx
- src/components/dashboard.tsx
- src/components/faq.tsx
- src/components/footer.tsx
- src/components/hamburgermenu.tsx
- src/components/landingpage.tsx
- src/components/navbar.tsx
- src/components/ourReach.tsx
- src/pages/_app.tsx
- src/pages/dashboardPage.tsx
- src/pages/landingPage.tsx
- src/pages/profile.tsx
- src/styles/globals.css
- tailwind.config.ts
- tsconfig.json
fixes #23 . Setting selective rendring of each circular Progresss Bar based on entry point of user's Window with a transitioned timing
> fix:#23 Trigerred Circular Bar

- src/components/dashboard.tsx
- src/styles/globals.css
Implement Sedgwick Ave in Dashboard report.
> fix: Font enhancement and box correction for Dashboard

- src/components/testes.tsx
- src/components/testimonials.tsx
- src/pages/landingPage.tsx
2 new files were created , one is the basic template of the testimonials(testes.tsx) and the other one which creates the carousel using that template(Testimonials.tsx)
> add responsive testimonials

- src/components/dashboardCard.tsx
- src/components/dashboardTab.tsx
- src/components/testes.tsx
- src/pages/dashboardPage.tsx
#53 added two files one for the dashboard task card and one for the tab component
> add dashboard tab

- src/components/carousel.tsx
- src/components/dashboard.tsx
- src/components/dashboardCard.tsx
- src/components/dashboardTab.tsx
- src/pages/dashboardPage.tsx
Added props and  links to social media icon for dashboard tabs
> add props , add links to social media

- src/components/abouttechnex.tsx
- src/components/landingpage.tsx
- src/components/navbar.tsx
- src/components/testimonials.tsx
Fixed about technex and date in the navbar and minor change in testimonials
> Fixed non responsiveness after recent pull

- package-lock.json
- package.json
- src/components/login.tsx
- src/components/register.tsx
- tailwind.config.ts
> Register Page Functioning 

- src/components/login.tsx
- src/components/register.tsx
- src/pages/api/login.ts
- src/pages/api/register.ts
The Register Page works perfectly fine but the account details still need to be verified by the backend server whose PR hasn't still been merged. The login page LGTM and its functionality cannot be tested until the accounts get stored after successful verification
> Login Page and Register Page Sorted

- package-lock.json
- package.json
- src/components/responsibility_card_Symbol_Bottom.tsx
- src/components/responsibility_card_symbol.tsx
- src/components/responsibility_carousel.tsx
Made the following changes:
1. Removed content cards
2. Shrank the image container and made more space for content
3. Centred the cards and improved responsiveness
> Updated responsibilities carousel

- src/components/dashboard.tsx
- src/components/leaderboard.tsx
- src/components/textbox.tsx
1. Added props on the dashboard
2. Removed courses part
> Modifiactions done on Dashboard

- src/components/AdminPage/TaskForm.tsx
- src/components/AdminPage/TaskList.module.css
- src/components/AdminPage/TaskList.tsx
- src/pages/adminPage.tsx
- src/styles/adminPage.module.css
- CRUD operations on tasks
- separate login option for admin
> [ADDED] Admin Page

- src/components/testimonials.tsx
> center the testimonials

- src/components/login.tsx
> Fixed Some Minor Issues

- src/components/AdminPage/TaskForm.tsx
- src/components/AdminPage/TaskList.module.css
- src/components/AdminPage/TaskList.tsx
- src/components/AdminPage/UnverifiedUsers.tsx
- src/pages/adminPage.tsx
> [ADDED] user verification by admin

- src/components/faq.tsx
- src/components/ourReach.tsx
> Modify `ourReach.tsx`

- src/components/abouttechnex.tsx
- src/components/ourReach.tsx
change of text in mentioned sections
> fix: change text in aboutus and whyca sections

- .gitignore
- src/components/dashboard.tsx
- src/components/leaderboard.tsx
Added Total Payments and Total Registrations in dashboard
Change user_name to first_name and last_name in leaderboard.
> Changes to leaderboard and dashboard

- src/components/forgotpassword.tsx
- src/components/resetpassword.tsx
- src/pages/api/forgotpassword.ts
- src/pages/api/resetpassword.ts
- src/pages/api/verifypassword.ts
- src/pages/forgotpassword.tsx
- src/pages/resetpassword.tsx
- added forget password in login page
- added forget password page to request otp
- added reset password page to enter new password
> fix: added forgot password feature

- src/components/footer.tsx
- src/components/hamburgermenu.tsx
- src/components/layout.tsx
- src/pages/profile.tsx
- src/styles/style.css
> Fixed `Profile` Page

- src/components/footer.tsx
- src/components/hamburgermenu.tsx
- src/components/layout.tsx
- src/pages/profile.tsx
- src/styles/style.css
Reverts technex-iit-bhu/CA_Frontend#158
> Revert "Fixed `Profile` Page"

- src/components/register.tsx
> Fixed the year in registration

- src/components/login.tsx
- src/components/resetpassword.tsx
added password criteria to reset password and / email in login
> fix: added password criteria to reset password and / email in login

- src/components/dashboard.tsx
- src/components/dashboardCard.tsx
- src/components/dashboardTab.tsx
- src/pages/dashboardPage.tsx
> Updated Comments and Submitted Tasks

- src/components/AdminPage/TaskList.tsx
- src/components/AdminPage/UnverifiedUsers.tsx
- src/components/dashboard.tsx
- src/components/dashboardCard.tsx
- src/components/dashboardTab.tsx
- src/components/faq.tsx
- src/components/forgotpassword.tsx
- src/components/login.tsx
- src/components/register.tsx
- src/components/resetpassword.tsx
- src/components/useFetchTasks.tsx
- src/pages/api/getProfile.ts
- src/pages/api/getSubmittedTasks.ts
- src/pages/api/getTasks.ts
- src/pages/api/verifypassword.ts
- src/pages/dashboardPage.tsx
Free ka mehnat hai. party de dijiye
> Created custom `useFetchtasks` hook to improve code readability

- src/components/dashboard.tsx
- src/components/navbar.tsx
> Fixed CA_Id Responsiveness
